import { Link } from 'react-router-dom';
import { ArrowUpRight, BookOpen, ArrowRight, Bookmark as BookmarkIcon } from 'lucide-react';
import { api } from '../api';
import { useResource } from '../hooks/use-resource';
import { PageHeader, LoadState, MetricCards, AttemptRow, StudyLink } from '../components/ui';
export function DashboardPage() {
  const resource = useResource(signal => api.dashboard(signal), 'dashboard');
  const data = resource.data;
  return <><PageHeader title="A little progress, every day." description="Pick up a concept, connect the dots, and keep building your foundation." action={<StudyLink />} /><LoadState {...resource} retry={resource.reload} />{data && <>
    <section className="relative mb-6 overflow-hidden rounded-2xl bg-slate-900 p-7 text-white md:p-9"><div className="pointer-events-none absolute -right-12 -top-24 h-80 w-80 rounded-full border-[40px] border-teal-500/10" /><p className="eyebrow text-teal-300!">Your next small step</p><h2 className="relative mt-3 max-w-md text-2xl font-medium leading-snug">Build confidence.<br />Understand the reasoning.</h2><p className="relative mt-3 max-w-lg text-sm leading-6 text-slate-400">Explore focused questions with immediate feedback. Take your time — understanding comes first.</p><Link to="/subjects" className="relative mt-6 inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-900">Explore subjects<ArrowRight size={15} /></Link><BookOpen className="absolute bottom-10 right-12 hidden h-24 w-24 text-teal-300/30 md:block" strokeWidth={1} /></section>
    <MetricCards metrics={data.performance} />
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="card p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="section-title">Recent activity</h2><p className="mt-1 text-xs text-slate-400">Your latest learning moments</p></div><Link to="/attempts" className="text-xs font-semibold text-teal-700">View all<ArrowUpRight size={14} className="ml-1 inline" /></Link></div>{data.recentAttempts.length ? data.recentAttempts.map(attempt => <AttemptRow attempt={attempt} key={attempt.id} />) : <div className="py-10 text-center"><BookOpen className="mx-auto text-slate-300" size={28} /><p className="mt-3 text-sm text-slate-500">Your first question is a great place to start.</p><Link to="/practice" className="mt-3 inline-block text-sm font-semibold text-teal-700">Try a practice question →</Link></div>}</section>
      <section className="card p-6"><div className="flex items-center justify-between"><h2 className="section-title">Saved for later</h2><span className="badge bg-slate-100 text-slate-500">{data.bookmarkCount}</span></div><p className="mt-1 text-xs text-slate-400">Concepts worth coming back to</p><div className="mt-5 space-y-3">{data.bookmarks.length ? data.bookmarks.slice(0, 3).map(bookmark => <Link key={bookmark.id} to={`/practice/${bookmark.questionId}`} className="flex gap-3 rounded-xl bg-slate-50 p-4 hover:bg-teal-50"><BookmarkIcon size={16} className="mt-0.5 shrink-0 text-teal-700" /><div><p className="line-clamp-2 text-sm leading-6">{bookmark.question?.prompt ?? 'Saved question'}</p><p className="mt-2 text-[11px] text-slate-400">{bookmark.question?.subject}</p></div></Link>) : <p className="py-8 text-sm leading-6 text-slate-500">Save a question during practice to revisit it here.</p>}</div><Link to="/bookmarks" className="secondary mt-5 w-full justify-center">Open bookmarks<ArrowRight size={15} /></Link></section>
    </div>
    <section className="mt-6 flex flex-wrap items-center justify-between gap-5 rounded-xl border border-teal-100 bg-teal-50 p-6"><div><h2 className="text-sm font-semibold text-teal-900">Latest-answer progress</h2><p className="mt-1 text-xs leading-5 text-teal-700">{data.progress.answered} unique questions · {data.progress.correct} latest answers correct · {data.progress.accuracy}% accuracy</p></div><Link to="/performance" className="text-sm font-semibold text-teal-800">Explore performance →</Link></section>
  </>}</>;
}
