import { Target, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { useResource } from '../hooks/use-resource';
import { PageHeader, LoadState, Empty, MetricCards, StudyLink, formatTime } from '../components/ui';
import type { Breakdown } from '../types';
function BreakdownList({ title, rows, kind }: { title: string; rows: Breakdown[]; kind: 'subject' | 'topic' }) {
  return <section className="card p-6"><h2 className="section-title">{title}</h2><p className="mt-1 text-xs text-slate-400">Accuracy across all attempts</p><div className="mt-6 space-y-6">{rows.map(row => <div key={row.id}><div className="flex items-center justify-between gap-3"><Link className="text-sm font-medium hover:text-teal-700" to={`/practice?${kind}Id=${row.id}`}>{row.name}<ArrowUpRight size={13} className="ml-1 inline text-slate-400" /></Link><span className="text-sm font-semibold text-teal-700">{row.accuracy}%</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{ width: `${row.accuracy}%` }} /></div><p className="mt-2 text-[11px] text-slate-400">{row.correctAttempts}/{row.totalAttempts} attempts correct · {formatTime(row.averageTimeTaken)} average</p></div>)}</div></section>;
}
export function PerformancePage() {
  const resource = useResource(signal => api.dashboard(signal), 'performance');
  const data = resource.data;
  return <><PageHeader title="See the bigger picture." eyebrow="Performance statistics" description="Notice your strengths, find your next focus, and celebrate steady progress." action={<StudyLink />} /><LoadState {...resource} retry={resource.reload} />{data && <><MetricCards metrics={data.performance} />{data.performance.totalAttempts ? <><section className="card mt-6 flex flex-wrap items-center gap-7 p-7"><div className="flex h-28 w-28 shrink-0 items-center justify-center rounded-full" style={{ background: `conic-gradient(#0f766e ${data.progress.accuracy}%, #e2e8f0 0)` }} role="img" aria-label={`Latest-answer accuracy ${data.progress.accuracy}%`}><div className="grid h-23 w-23 place-items-center rounded-full bg-white text-2xl font-semibold text-teal-800">{data.progress.accuracy}%</div></div><div><p className="eyebrow">Latest-answer accuracy</p><h2 className="mt-2 text-lg font-semibold">A snapshot of your current understanding.</h2><p className="mt-3 text-sm leading-6 text-slate-500">{data.progress.correct} latest answers correct out of {data.progress.answered} unique questions.<br />The cards above include every attempt, including retries.</p></div></section><div className="mt-6 grid gap-6 lg:grid-cols-2"><BreakdownList title="By subject" rows={data.performance.bySubject} kind="subject" /><BreakdownList title="By topic" rows={data.performance.byTopic} kind="topic" /></div><div className="mt-6 flex items-center gap-4 rounded-xl bg-teal-50 p-5 text-teal-800"><Target size={24} className="shrink-0" /><p className="text-sm leading-6">Use this view to choose what to review next. Accuracy is a practice metric, not a predicted exam score.</p></div></> : <div className="mt-6"><Empty title="Your progress will take shape here" text="Answer a few questions to see your strengths, timing, and subject breakdowns." action={<StudyLink />} /></div>}</>}</>;
}
